server:
  port: 3000

spring:
  application:
    name: payment-service

  security:
    user:
      name: jack
      password: q1w2e3r4

config:
  info: master branch,payment-service-dev.yml,version=9999
  password2000: 123123
  password2001: '{cipher}AQB+h/Qu6aoNiek1cA+7NzWGCbmNqYfqKBca9mAFEhWTNBX2+HohAQnc0qltQbMe2vw7NCVg+p49kDkeFXoEGHKyIRrWrxcuNWyHaMjl5YvHDs1HPJo3oqSXeO7SfJQKhWUczsT991WJGlScreSqqI1N6iZIA0raxLEqSfBkm40sDB7FQ9f27jlcALn0ubjZccJ26oL2Klu30EBXMRiVgUbARWIKH5Ld0OdNdxyMckUpC9L8rEzpw/iTfBaLsOe2X/nRYLVYSgMnJsIQyw9PTkFvsO4GAJiA7eeTrn62BMAphI/+uTPAhazU/8PNehdHrDr5c17TLdcDIv1RzT3sp0lHCnfn0Yv1XrHXjW80O/XQFI3W5l3yVjeAe/3rejhUJKA='

management:
  endpoints:
    web: # Actuator HTTP 配置项，对应 WebEndpointProperties 配置类
      exposure:
        include: refresh # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
